### ISSUE TITLE
What are the breaking changes of version 3?

### ISSUE THREAD

**Issue by lsund** [baruchiro/use-route-as-state#73]
Could you include a Changelog / needed actions to update? Thanks

**Comment by baruchiro** [comment]
I wrote in the commit and changed the docs, but I don't using releases.

What is your suggestion for changelog? Separated file? End of the docs?

**Comment by lsund** [comment]
> I wrote in the commit and changed the docs, but I don't using releases.

Sorry, which commit are you referring to ? I only see "v3.0.0 useState interface **breaking**" and it is not clear to me what is breaking. Is it only the names of the main imports? 

> Separated file? End of the docs?

Doesn't matter to me, just need to have it clearly documented somewhere what I need to do to continue using the library.

**Comment by baruchiro** [comment]
OK, for now, I will just tell you that actually there are no breaking changes. I planed to break something, but instead, I moved the old code to be alongside the new, so if you upgrade the library, you will get a deprecation warning for the library hooks.

I created a new version (with new names) of the hooks to be more like `useState`. In the end, it means that every time you put an object inside the update method, it will **replace** the state instead of **update**, so you don't need to pass properties with `undefined` to remove them from the QueryString. If you want to **update** the current state, you can pass a `(prev) => new state` function.

I will write a changelog after.

Sorry, I have no so much experience with public libraries, I need help from users to learn how to do that right.
Thanks for choosing my library.

**Comment by lsund** [comment]
>  so you don't need to pass properties with undefined to remove them from the QueryString

Thats great, thank you for clarifying. No problem, then it was just a misunderstanding.

**Comment by baruchiro** [comment]
Finally, I created a [CHANGELOG](https://github.com/baruchiro/use-route-as-state/blob/master/CHANGELOG.md) file.

I tried some auto generators, but they are not good for me, so for now I will create it manually.

**Comment by lsund** [comment]
Thanks alot!
